filter:
    excluded_paths: [vendor/*, web/*]
    paths: [bootstrap.php, src/*]

before_commands:
    - "composer install --prefer-source"

tools:
    php_code_coverage: true
    php_code_sniffer:
        filter:
            paths: [src/*]
            excluded_paths: [vendor/*, web/*, test/*]
        config:
            standard: PSR2
    php_cpd: true
    php_pdepend: true
    php_loc: true
    php_mess_detector: true
    php_analyzer: true
